- name: Install php-fpm
  apt:
    name: php7.4-fpm

- name: Php-fpm started
  systemd:
    name: php7.4-fpm
    state: started
    enabled: yes

- name: Php-fpm config
  template:
    src: my-pool.conf.j2
    dest: /etc/php/7.4/fpm/pool.d/my-pool.conf
    owner: root
    group: root
    mode: 0644
  notify: Php-fpm reload
