- name: Install nginx
  apt:
    name: nginx

- name: Nginx started
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: Nginx main config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify: Nginx reload

- name: Nginx conf.d
  file:
    path: /etc/nginx/conf.d
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Nginx main site config
  template:
    src: main.conf.j2
    dest: /etc/nginx/conf.d/main.conf
    owner: root
    group: root
    mode: 0644
  notify: Nginx reload

- name: Nginx proxy site config
  template:
    src: proxy.conf.j2
    dest: /etc/nginx/conf.d/proxy.conf
    owner: root
    group: root
    mode: 0644
  notify: Nginx reload
